### ISSUE TITLE
Add missing image for Turborepo

### ISSUE THREAD

**Issue by dtinth** [fresh-app/fresh-app.github.io#2]
## Background

Right now the website is missing an image for Turborepo.

![image](https://user-images.githubusercontent.com/193136/193738568-43816580-01d8-4ada-ae82-5f4536e04e5c.png)

## Task

- Add a Turborepo image and make it show on the home page.
  - The image files should be put in `.vitepress/icons`.
  - The logic to select which icon to display should be updated. The logic lives in `.vitepress/icons/index.ts`.
  - SVG file preferred, if use PNG, image size must be at least 64x64.
- Your PR should change only the files in `.vitepress/icons`.
- Please include a screenshot in your PR to confirm that it is working.

## How to develop this project

The README file is currently missing. Current steps to develop this project is as follows:

- Install deps
   ```
   yarn
   ```
- Load latest build data
   ```
   yarn tsx scripts/load.ts
   ```
- Generate page files
   ```
   yarn tsx scripts/generate.ts
   ```
- Start development server
   ```
   yarn build
   ```

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

**Comment by NeilAn99** [comment]
Hi, I would like to work on this issue.

**Comment by NeilAn99** [comment]
Hi, I'm having trouble starting the development server so I can't test my code. What steps should I take after running `yarn build`?

**Comment by thedroiddiv** [comment]
![Screenshot 2022-10-04 at 12 10 40 PM](https://user-images.githubusercontent.com/69595691/193751313-7f9fd241-b6e2-4852-83c6-48c44e7d12ed.png)

@dtinth Would this icon be preferred?

**Comment by dtinth** [comment]
@NeilAn99 The files will be output in `.vitepress/dist` and you can use a web server like [http-server](https://www.npmjs.com/package/http-server) to preview. Next time when you have trouble please send the logs so I can see what you mean by “having trouble.”

**Comment by dtinth** [comment]
@divyansh-dxn Yes, looks good, thanks!

**Comment by dtinth** [comment]
@NeilAn99 I saw that you already committed some code, but @divyansh-dxn opened a PR first, so I merged that in first.

So just for this case, feel free to open a PR and I will add “hacktoberfest-accepted” label and close it. Your PR will likely have merge conflicts and you don’t have to fix it.
