### ISSUE TITLE
Add link to `github.dev` in homepage

### ISSUE THREAD

**Issue by dtinth** [fresh-app/fresh-app.github.io#5]
## Background

On the Fresh App Factory homepage <https://fresh-app.github.io/> there are icon links for each template.

Sometimes I want to quickly inspect a template contents in VS Code. Great thing that [we now have GitHub.dev](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor).

## Task

- Add a link to the template repository on github.dev according to the image below. It is similar to the “View repository” link but links to `github.dev` instead of `github.com`. The icon should be the same color as other icons.
   ![image](https://user-images.githubusercontent.com/193136/194042553-4e93c02e-d777-4bc8-b56a-8c4cd7be2000.png)
- Your PR should change a single file `.vitepress/ProjectList.vue`
- Please include a screenshot in your PR to confirm that it is working.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

If you encounter any problem, please include relevant logs and screenshot so it’s easy to troubleshoot.

**Comment by RachitGarg-12** [comment]
Hey , can you assign me this issue.

**Comment by iabhaybisht** [comment]
Can you assign me this issue ?

**Comment by dtinth** [comment]
@RachitGarg-12 Please go ahead, thanks!

@Znoy108x Sorry, I can only assign to one person on a single issue, but there will be other issues in the future for sure.

**Comment by dtinth** [comment]
@RachitGarg-12 Unfortunately the PR #6 was submitted before you fork the repo. There is currently one more issue that can be worked on (#4).

I have also clarified the meaning of getting assigned to an issue:

> **Getting assigned to an issue is for informational purpose only and is not a reservation.** It is merely to provide a signal to avoid duplicated efforts, but does not prevent others from working on the same issue. The first valid PR that resolves the issue will be merged, regardless of who gets assigned to the issue. However, if you have already started working on the issue where you got assigned, but someone else submitted a valid PR before you, you can still submit a valid PR and I will add a `hacktoberfest-accepted` label and close it.
