### ISSUE TITLE
[FEATURE] Open graph

### ISSUE THREAD

**Issue by Nakamcode** [fresh-app/fresh-app.github.io#7]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

### The benefit of OPEN GRAPH

- All of the major social networks recognize open graph tags. ...
- Open graph tags were built for social media. ...
- Differentiates social previews from search previews. ...
- You have control over how your content is seen on social—whether you share it or someone else does.

### Here's how the page appears without an open graph on social media and search engines
![captures_chrome-capture-2022-9-5](https://user-images.githubusercontent.com/89482825/194146261-966dab18-5bbd-4657-84bd-14fcc6351310.png)

**Comment by dtinth** [comment]
@Nakamcode Good idea! As a start you can use the image URL in README, but suggestions for a better image is welcome!

**Comment by Nakamcode** [comment]
sure, I will like to design a new one for it
