### ISSUE TITLE
Fix errors when opening TypeScript files in VS Code

### ISSUE THREAD

**Issue by dtinth** [fresh-app/fresh-app.github.io#8]
## Background

As reported by @Savio629 in #4, when setting up the project, opening the project in VS Code, and viewing `.vitepress/icons/index.ts`, there is a lot of errors shown.

Despite that, the website can be built successfully, so there is not a problem with the code. This is probably an error in configuring `tsconfig.json` and `d.ts` files. It is not properly set up to integrate with the IDE yet.

<img src="https://user-images.githubusercontent.com/91362589/194265105-3b81c8b8-5913-48e4-926e-3b43c66b51b9.png" width="600">

## Task

- Make it so that when opening this file, you don’t see red squiggly errors lines anymore.
- Your PR should not change the code as it is already working — only configs related to TypeScript and VSCode allowed.
   - This means it should only change `.d.ts` or `tsconfig.json` or other config files.
   - Maybe some package has to be installed, so changes to `package.json` is fine as well.
   - If you have any questions, feel free to ask in this issue.
- Please include a screenshot in your PR to confirm that it is working.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

**Getting assigned to an issue is NOT a reservation.** It is simply to let others know that someone is already working on it to avoid duplicated efforts. The first person who submits a valid Pull Request (PR) that resolves the issue will have their PR merged, regardless of who was assigned to the issue. However, if you are assigned to an issue and start working on it, but someone else submits a valid PR before you, you can still submit a valid PR even if it has conflicts. The PR will be given the "hacktoberfest-accepted" label and the issue will be closed.

If you encounter any problem, please __include relevant logs and screenshot__ so it’s easy to troubleshoot.

**Comment by haidarrifki** [comment]
hi @dtinth, can i work on this issue?

**Comment by haidarrifki** [comment]
i just made a PR #9 please review it, thanks!
